### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by GoldOnMyRist** [GoldOnMyRist/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by EndlessSummer7** [comment]
### **DONALD TRUMP**

- https://www.fb.com/DonaldTrump
- realDonaldTrump@whitehouse.gov
- https://twitter.com/realDonaldTrump
- https://www.instagram.com/realDonaldTrump/

**Comment by GoldOnMyRist** [comment]
I'm sure it will be usefull for my site. Thanks again!
